In [251]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [252]:
data = pd.read_csv('pregnancy dataset.csv')

In [253]:
data.head()

Age  Systolic BP  Diastolic   BS  Body Temp   BMI  Previous Complications  \
0   22         90.0       60.0  9.0        100  18.0                     1.0   
1   22        110.0       70.0  7.1         98  20.4                     0.0   
2   27        110.0       70.0  7.5         98  23.0                     1.0   
3   20        100.0       70.0  7.2         98  21.2                     0.0   
4   20         90.0       60.0  7.5         98  19.7                     0.0   

   Preexisting Diabetes  Gestational Diabetes  Mental Health  Heart Rate  \
0                   1.0                     0              1        80.0   
1                   0.0                     0              0        74.0   
2                   0.0                     0              0        72.0   
3                   0.0                     0              0        74.0   
4                   0.0                     0              0        74.0   

  Risk Level  
0       High  
1        Low  
2        Low  
3        Low  
4        Low

In [254]:
data.shape

(1205, 12)

In [255]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1205 entries, 0 to 1204
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Age                     1205 non-null   int64  
 1   Systolic BP             1200 non-null   float64
 2   Diastolic               1201 non-null   float64
 3   BS                      1203 non-null   float64
 4   Body Temp               1205 non-null   int64  
 5   BMI                     1187 non-null   float64
 6   Previous Complications  1203 non-null   float64
 7   Preexisting Diabetes    1203 non-null   float64
 8   Gestational Diabetes    1205 non-null   int64  
 9   Mental Health           1205 non-null   int64  
 10  Heart Rate              1203 non-null   float64
 11  Risk Level              1187 non-null   object 
dtypes: float64(7), int64(4), object(1)
memory usage: 113.1+ KB


In [256]:
data.isnull().sum()

Age                        0
Systolic BP                5
Diastolic                  4
BS                         2
Body Temp                  0
BMI                       18
Previous Complications     2
Preexisting Diabetes       2
Gestational Diabetes       0
Mental Health              0
Heart Rate                 2
Risk Level                18
dtype: int64

In [257]:
data.describe()

Age  Systolic BP    Diastolic           BS    Body Temp  \
count  1205.000000  1200.000000  1201.000000  1203.000000  1205.000000   
mean     27.482988   116.819167    77.166528     7.501064    98.395851   
std       9.196765    18.715502    14.305148     3.049522     1.088363   
min      10.000000    70.000000    40.000000     3.000000    97.000000   
25%      21.000000   100.000000    65.000000     6.000000    98.000000   
50%      25.000000   120.000000    80.000000     6.900000    98.000000   
75%      31.000000   130.000000    90.000000     7.900000    98.000000   
max      65.000000   200.000000   140.000000    19.000000   103.000000   

               BMI  Previous Complications  Preexisting Diabetes  \
count  1187.000000             1203.000000           1203.000000   
mean     23.315080                0.175395              0.288446   
std       3.875682                0.380463              0.453228   
min       0.000000                0.000000              0.000000   
25%      20.450000                0.000000              0.000000   
50%      23.000000                0.000000              0.000000   
75%      25.000000                0.000000              1.000000   
max      37.000000                1.000000              1.000000   

       Gestational Diabetes  Mental Health   Heart Rate  
count           1205.000000     1205.00000  1203.000000  
mean               0.117842        0.33444    75.817124  
std                0.322555        0.47199     7.227338  
min                0.000000        0.00000    58.000000  
25%                0.000000        0.00000    70.000000  
50%                0.000000        0.00000    76.000000  
75%                0.000000        1.00000    80.000000  
max                1.000000        1.00000    92.000000

In [258]:
data.columns

Index(['Age', 'Systolic BP', 'Diastolic', 'BS', 'Body Temp', 'BMI',
       'Previous Complications', 'Preexisting Diabetes',
       'Gestational Diabetes', 'Mental Health', 'Heart Rate', 'Risk Level'],
      dtype='object')

In [259]:
mean_systolic = data['Systolic BP'].mean()
mean_systolic

116.81916666666666

In [260]:
data['Systolic BP'] = data['Systolic BP'].fillna(mean_systolic)

In [261]:
data['Systolic BP'].isnull().sum()

0

In [262]:
mean_diastolic = data['Diastolic'].mean()
mean_diastolic

77.16652789342214

In [263]:
data['Diastolic'] = data['Diastolic'].fillna(mean_diastolic)

In [264]:
data['Diastolic'].isnull().sum()

0

In [265]:
mean_bs = data['BS'].mean()
mean_bs

7.501064006650041

In [266]:
data['BS'] = data['BS'].fillna(mean_bs)

In [267]:
data['BS'].isnull().sum()

0

In [268]:
mean_bmi = data['BMI'].mean()
mean_bmi

23.3150800336984

In [269]:
data['BMI'] = data['BMI'].fillna(mean_bmi)

In [270]:
data['BMI'].isnull().sum()

0

In [271]:
data['Previous Complications'] = data['Previous Complications'].fillna(0)

In [272]:
data['Previous Complications'].isnull().sum()

0

In [273]:
data['Preexisting Diabetes'] = data['Preexisting Diabetes'].fillna(0)

In [274]:
data['Preexisting Diabetes'].isnull().sum()

0

In [275]:
mean_hr = data['Heart Rate'].mean()

In [276]:
data['Heart Rate'] = data['Heart Rate'].fillna(mean_hr)

In [277]:
data['Heart Rate'].isnull().sum()

0

In [306]:
data = data.dropna(subset = ['Risk Level'])

In [308]:
data.isnull().sum()

Age                       0
Systolic BP               0
Diastolic                 0
BS                        0
Body Temp                 0
BMI                       0
Previous Complications    0
Preexisting Diabetes      0
Gestational Diabetes      0
Mental Health             0
Heart Rate                0
Risk Level                0
dtype: int64

In [310]:
data['Risk Level'].value_counts()

Risk Level
Low     713
High    474
Name: count, dtype: int64

In [314]:
data['Risk Level'] = data['Risk Level'].map({'Low': 0, 'High': 1})

In [318]:
data['Risk Level'].unique()

array([1, 0], dtype=int64)

In [324]:
X = data.drop('Risk Level', axis = 1)
y = data['Risk Level']

In [326]:
from sklearn.model_selection import train_test_split

In [328]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [336]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

In [338]:
pipe = make_pipeline(StandardScaler(), LogisticRegression(max_iter = 1000))
pipe.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression', LogisticRegression(max_iter=1000))])

In [340]:
y_log_pred = pipe.predict(X_test)
y_log_pred

array([0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0], dtype=int64)

In [342]:
from sklearn.metrics import classification_report, confusion_matrix

In [348]:
confusion_matrix(y_test, y_log_pred)

array([[139,   1],
       [  2,  96]], dtype=int64)

In [350]:
classification_report(y_test, y_log_pred)

'              precision    recall  f1-score   support\n\n           0       0.99      0.99      0.99       140\n           1       0.99      0.98      0.98        98\n\n    accuracy                           0.99       238\n   macro avg       0.99      0.99      0.99       238\nweighted avg       0.99      0.99      0.99       238\n'

In [352]:
knn = KNeighborsClassifier(n_neighbors = 5)
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [354]:
y_knn_pred = knn.predict(X_test)
y_knn_pred

array([0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int64)

In [356]:
confusion_matrix(y_test, y_knn_pred)

array([[136,   4],
       [ 21,  77]], dtype=int64)

In [358]:
classification_report(y_test, y_knn_pred)

'              precision    recall  f1-score   support\n\n           0       0.87      0.97      0.92       140\n           1       0.95      0.79      0.86        98\n\n    accuracy                           0.89       238\n   macro avg       0.91      0.88      0.89       238\nweighted avg       0.90      0.89      0.89       238\n'